repos:
  # Rust Code Check and Format 
  - repo: https://github.com/Narsil/pre-commit-rust
    rev: 2eed6366172ef2a5186e8785ec0e67243d7d73d0
    hooks:
      - id: fmt
        name: "Rust (fmt)"
      - id: clippy
        name: "Rust (clippy)"
        args:
          [
            "--tests",
            "--examples",
            "--",
            "-Dwarnings",
          ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.md$
        args: ["--prose-wrap", "always"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: ["--disable", "MD013"]  
